### PR TITLE
Water splash fix in dev branch.

### PR DESCRIPTION
**Pull request by Nukiloco**

### CODE REVIEW

**Comment by JShorthouse** [comment]
Can you try making the bullet changes I mentioned in the previous PR?

**Comment by Nukiloco** [comment]
Should the default distance in case nothing is put into the input be 65?

**Comment by JShorthouse** [comment]
Since distance was already an existing argument I'm sure it's safe to assume the rest of the code will always provide a number.

**Comment by Nukiloco** [comment]
Should we use MeleeTrace or ClipHullMeleeTrace?

**Comment by JShorthouse** [comment]
If the changes you've made fix the infinite distance splashes then keep using ClipHullMeleeTrace

**Comment by Nukiloco** [comment]
I will have to test it out later since I need to go somewhere but I updated my server with the new code. When I get back I will test it out.

**Comment by Nukiloco** [comment]
I'm trying to try this out though now using bots produces errors in the console, the error is in line 286 that it tried to index tab a nil value. This is in obj_player_extend.lua and in sh_animations.lua. I don't think this has anything to do with the water splash issue?

```
[ERROR] gamemodes/zombiesurvival/gamemode/obj_player_extend.lua:286: attempt to index local 'tab' (a nil value)
  1. CallZombieFunction - gamemodes/zombiesurvival/gamemode/obj_player_extend.lua:286
   2. unknown - gamemodes/zombiesurvival/gamemode/sh_animations.lua:27
```

**Comment by JShorthouse** [comment]
Are you making changes while the server is running?

Everything tends to go funky if you mess with serverside stuff while the server is up, you'll have to restart after each change.

**Comment by Nukiloco** [comment]
I changed nothing while it was running and apparently that just started to happen? Also after server reboot spawning a bot in now doesn't glitch the game? So that was just some random error that happened?

**Comment by Nukiloco** [comment]
Tested it and using ClipHullMeleeTrace and MeleeTrace works perfectly fine when the bot is crouching.
Now I will choose to using MeleeTrace again but I still have no clue why the LagCompensation was commented it out in shared.lua, maybe because it was already included inside of ClipHullMeleeTrace? I'm going to leave those now uncommented because I think it's important to MeleeTrace.

**Comment by Nukiloco** [comment]
Just wondering do you have a Steam or Discord that I can get in contact with you? Thanks!

**Comment by Nukiloco** [comment]
I adjusted the size model and position on the Health GUI so you now can't see the model cutting out very often.

**Comment by JShorthouse** [comment]
If setting the bullet distance fixed the splash issue then can you revert your changes to shared.lua?
There's no need to switch the trace method if you've fixed the root problem.

Also I appreciate you trying to fix other issues but can you please do so in another pull request?

**Comment by Nukiloco** [comment]
Sure here you go, reverted health gui changes and weapon base melee now uses ClipHullMeleeTrace.

**Comment by JShorthouse** [comment]
Alright, thank you.

Have you tested that adding the distance parameter to bullets fixes the problem?
If so, would you be able to reset your dev branch back to the state of this repo and then make the single change again? I don't really want to merge a mess of 7 unnecessary commits.

p.s. this line ```distance = distance``` isn't needed :)

**Comment by Nukiloco** [comment]
https://github.com/JShorthouse/zombiesurvivalfixes/pull/9/commits/43e6954724653992ead621bc6c9f54c3d068bda1 I did fix distance = distance earlier but ;_; that's a lot of changes but I don't know if I can reset my repo at this point, I guess I have to make another pull request with another branch and just change the one line in that one file?

**Comment by JShorthouse** [comment]
Just rollback your dev branch to before you made any changes, and then make the bullet commit again.

This PR should then clear up.

**Pull request closed without merging**
